apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main
spec:
  rules:
  - host: test.local
    http: 
      paths:
      - path: /green
        pathType: Prefix
        backend:
          service:
            name: green
            port:
              number: 80
      - path: /blue
        pathType: Prefix
        backend:
          service:
            name: blue
            port:
              number: 80
  - host: green.test.local
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: green
            port:
              number: 80
  - host: blue.test.local
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blue
            port:
              number: 80
