apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubesleeper

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubesleeper
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - services
      - pods
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubesleeper
subjects:
  - kind: ServiceAccount
    name: kubesleeper
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kubesleeper
  apiGroup: rbac.authorization.k8s.io