[book]
authors = ["kubesleeper contributors"]
language = "en"
src = "src"
title = "Kubesleeper"

[output.html]
cname = "kubesleeper.com"
git-repository-url = "https://github.com/kubesleeper/kubesleeper"
additional-css = ["theme/custom.css"]
default-theme = "light"
preferred-dark-theme = "coal"

[output.html.print]
enable = false  
