name: Checking commit format

on:
  pull_request:

jobs:
  checking_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout du d√©clencheur
        uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0

      - name: Setup
        run: |
          git log origin/c14-test..HEAD
          wget https://github.com/eloi-menaud/c14/releases/download/v2.0.0/c14
          chmod +x c14
      
      - name: Checking commit format with c14
        run: |
          echo "checking all commit since the last one on '$GITHUB_BASE_REF' branch"
          ./c14 --report --from-merge-base origin/$GITHUB_BASE_REF
          cat c14-report.json

