name: Versioning and Releasing

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        run: |
          wget https://github.com/eloi-menaud/c14/releases/download/v3.0.0/c14
          chmod +x c14
      
      - name: Get version from c14
        id: get_version
        run: |
          echo "get new version from last version tag"
          sanitized_version=$(./c14 --strict --report --target src | sed s/^v//)
          cat c14-report.json
          echo
          if test "$sanitized_version" == "0.0.0"
          then
            echo "Version has not been changed, skipping"
            sanitized_version=""
          fi
          echo "version=$sanitized_version" >> $GITHUB_OUTPUT

  release:
    needs: version
    runs-on: ubuntu-latest
    
    if: ${{ needs.version.outputs.version != '' }} 
    
    permissions:
      contents: write # for 'git push' and 'action-gh-release'

    steps:
      - name: Code Checkout pour la Release
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Override cargo.toml version
        run: |
          version="${{ needs.version.outputs.version }}"
          echo "Overriding Cargo.toml with version: $version"
          sed -i "s/^version\s*=.*$/version = \"${version}\"/" Cargo.toml
          git diff Cargo.toml
      
      - name: Building kubesleeper
        run: |
          cd src
          cargo build --release
      
      - name: Pushing new Cargo.toml
        run: |
          git add Cargo.toml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "feat: auto ci versioning v${{ needs.version.outputs.version }} [skip ci]"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.version.outputs.version }}
          name: Release v${{ needs.version.outputs.version }}
          files: src/target/release/kubesleeper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}